name: FeelsGoodVapor
favicon: null
layout_spectrum: 0.25250770593993366
typography_spectrum: 0.07815844495780766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20618669502437115
  lightness: 0.4897001488134265
  saturation: 0.07257015048526227
  rhythmicContrast: 0.9439547804649919
purpose: []
